In [39]:
import pandas as pd
df_x = pd.read_csv("C:\\Users\\Admin\\Downloads\\dataset and all\\training_set_features.csv")
df_y = pd.read_csv("C:\\Users\\Admin\\Downloads\\dataset and all\\training_set_labels.csv")

In [40]:
df_x.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [41]:
dff = df_x.merge(df_y, on='respondent_id', how='left')
(dff.head())

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,xyz_vaccine,seasonal_vaccine
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN,0,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe,0,1
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo,0,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN,0,1
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb,0,0

In [42]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

cols_to_scale = [
    'opinion_xyz_vacc_effective',
    'opinion_xyz_risk',
    'opinion_xyz_sick_from_vacc',
    'opinion_seas_vacc_effective',
    'opinion_seas_risk',
    'opinion_seas_sick_from_vacc'
]

scaler = MinMaxScaler(feature_range=(0, 1))
dff[cols_to_scale] = scaler.fit_transform(dff[cols_to_scale])

print(dff[cols_to_scale].head())

   opinion_xyz_vacc_effective  opinion_xyz_risk  opinion_xyz_sick_from_vacc  \
0                         0.5              0.00                        0.25
1                         1.0              0.75                        0.75
2                         0.5              0.00                        0.00
3                         0.5              0.50                        1.00
4                         0.5              0.50                        0.25

   opinion_seas_vacc_effective  opinion_seas_risk  opinion_seas_sick_from_vacc
0                         0.25               0.00                         0.25
1                         0.75               0.25                         0.75
2                         0.75               0.00                         0.25
3                         1.00               0.75                         0.00
4                         0.50               0.00                         0.75

In [43]:
df_x['age_group'].unique()

array(['55 - 64 Years', '35 - 44 Years', '18 - 34 Years', '65+ Years',
       '45 - 54 Years'], dtype=object)

In [44]:
age_group_means = dff.groupby('age_group')[['xyz_vaccine', 'seasonal_vaccine']].mean()
age_group_means

               xyz_vaccine  seasonal_vaccine
age_group
18 - 34 Years     0.190029          0.284564
35 - 44 Years     0.197765          0.362526
45 - 54 Years     0.194731          0.401298
55 - 64 Years     0.242855          0.511235
65+ Years         0.226655          0.673681

In [45]:
age_group_means['mean_vaccine'] = age_group_means.mean(axis=1)
age_group_mean_mapping = age_group_means['mean_vaccine'].to_dict()
(age_group_mean_mapping)

{'18 - 34 Years': 0.23729626078619365,
 '35 - 44 Years': 0.2801455301455301,
 '45 - 54 Years': 0.2980145093547155,
 '55 - 64 Years': 0.3770447600215711,
 '65+ Years': 0.4501680549466608}

In [46]:
dff['age_group'] = dff['age_group'].map(age_group_mean_mapping)
print(dff['age_group'])

0        0.377045
1        0.280146
2        0.237296
3        0.450168
4        0.298015
           ...
26702    0.450168
26703    0.237296
26704    0.377045
26705    0.237296
26706    0.450168
Name: age_group, Length: 26707, dtype: float64

In [47]:
dff['education'].unique()

array(['< 12 Years', '12 Years', 'College Graduate', 'Some College', nan],
      dtype=object)

In [48]:
dff['education'] = dff['education'].fillna('Unknown')

In [49]:
dff['education'].unique()

array(['< 12 Years', '12 Years', 'College Graduate', 'Some College',
       'Unknown'], dtype=object)

In [50]:
education_mapping = {
    'Unknown': 0,
    '< 12 Years': 0.20,
    '12 Years': 0.40,
    'Some College': 0.60,
    'College Graduate': 0.80
}
dff['education'] = dff['education'].map(education_mapping)

In [56]:
import pandas as pd
columns_to_encode = [
    'race', 'sex', 'income_poverty', 'marital_status', 'rent_or_own',
    'employment_status', 'hhs_geo_region', 'census_msa',
    'household_adults', 'household_children', 'employment_industry',
    'employment_occupation'
]
dff = pd.get_dummies(dff, columns=columns_to_encode, drop_first=True)

   respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              0          1.0            0.0                        0.0
1              1          3.0            2.0                        0.0
2              2          1.0            1.0                        0.0
3              3          1.0            1.0                        0.0
4              4          2.0            1.0                        0.0

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   0.0                   0.0                    0.0
1                   1.0                   0.0                    1.0
2                   1.0                   0.0                    0.0
3                   1.0                   0.0                    1.0
4                   1.0                   0.0                    1.0

   behavioral_large_gatherings  behavioral_outside_home  \
0                          0.0                      1.0
1                          0.0                      1.0
2                          0.0                      0.0
3                          1.0                      0.0
4                          1.0                      0.0

   behavioral_touch_face  ...  employment_occupation_qxajmpny  \
0                    1.0  ...                               0
1                    1.0  ...                               0
2                    0.0  ...                               0
3                    0.0  ...                               0
4                    1.0  ...                               0

   employment_occupation_rcertsgn  employment_occupation_tfqavkke  \
0                               0                               0
1                               0                               0
2                               0                               0
3                               0                               0
4                               0                               0

   employment_occupation_ukymxvdu  employment_occupation_uqqtjvyb  \
0                               0                               0
1                               0                               0
2                               0                               0
3                               0                               0
4                               0                               0

   employment_occupation_vlluhbov  employment_occupation_xgwztkwe  \
0                               0                               0
1                               0                               1
2                               0                               0
3                               0                               0
4                               0                               0

   employment_occupation_xqwwgdyp  employment_occupation_xtkaffoo  \
0                               0                               0
1                               0                               0
2                               0                               1
3                               0                               0
4                               0                               0

   employment_occupation_xzmlyyjv
0                               0
1                               0
2                               0
3                               0
4                               0

[5 rows x 95 columns]

In [57]:
dff.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,employment_occupation_qxajmpny,employment_occupation_rcertsgn,employment_occupation_tfqavkke,employment_occupation_ukymxvdu,employment_occupation_uqqtjvyb,employment_occupation_vlluhbov,employment_occupation_xgwztkwe,employment_occupation_xqwwgdyp,employment_occupation_xtkaffoo,employment_occupation_xzmlyyjv
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0,0,0,0,0,0,1,0,0,0
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,1,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0

In [58]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26707 entries, 0 to 26706
Data columns (total 95 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   respondent_id                         26707 non-null  int64
 1   xyz_concern                           26615 non-null  float64
 2   xyz_knowledge                         26591 non-null  float64
 3   behavioral_antiviral_meds             26636 non-null  float64
 4   behavioral_avoidance                  26499 non-null  float64
 5   behavioral_face_mask                  26688 non-null  float64
 6   behavioral_wash_hands                 26665 non-null  float64
 7   behavioral_large_gatherings           26620 non-null  float64
 8   behavioral_outside_home               26625 non-null  float64
 9   behavioral_touch_face                 26579 non-null  float64
 10  doctor_recc_xyz                       24547 non-null  float64
 11  doctor_recc_seasonal                  24547 non-null  float64
 12  chronic_med_condition                 25736 non-null  float64
 13  child_under_6_months                  25887 non-null  float64
 14  health_worker                         25903 non-null  float64
 15  health_insurance                      14433 non-null  float64
 16  opinion_xyz_vacc_effective            26316 non-null  float64
 17  opinion_xyz_risk                      26319 non-null  float64
 18  opinion_xyz_sick_from_vacc            26312 non-null  float64
 19  opinion_seas_vacc_effective           26245 non-null  float64
 20  opinion_seas_risk                     26193 non-null  float64
 21  opinion_seas_sick_from_vacc           26170 non-null  float64
 22  age_group                             26707 non-null  float64
 23  education                             26707 non-null  float64
 24  xyz_vaccine                           26707 non-null  int64
 25  seasonal_vaccine                      26707 non-null  int64
 26  race_Hispanic                         26707 non-null  uint8
 27  race_Other or Multiple                26707 non-null  uint8
 28  race_White                            26707 non-null  uint8
 29  sex_Male                              26707 non-null  uint8
 30  income_poverty_> $75,000              26707 non-null  uint8
 31  income_poverty_Below Poverty          26707 non-null  uint8
 32  marital_status_Not Married            26707 non-null  uint8
 33  rent_or_own_Rent                      26707 non-null  uint8
 34  employment_status_Not in Labor Force  26707 non-null  uint8
 35  employment_status_Unemployed          26707 non-null  uint8
 36  hhs_geo_region_bhuqouqj               26707 non-null  uint8
 37  hhs_geo_region_dqpwygqj               26707 non-null  uint8
 38  hhs_geo_region_fpwskwrf               26707 non-null  uint8
 39  hhs_geo_region_kbazzjca               26707 non-null  uint8
 40  hhs_geo_region_lrircsnp               26707 non-null  uint8
 41  hhs_geo_region_lzgpxyit               26707 non-null  uint8
 42  hhs_geo_region_mlyzmhmf               26707 non-null  uint8
 43  hhs_geo_region_oxchjgsf               26707 non-null  uint8
 44  hhs_geo_region_qufhixun               26707 non-null  uint8
 45  census_msa_MSA, Principle City        26707 non-null  uint8
 46  census_msa_Non-MSA                    26707 non-null  uint8
 47  household_adults_1.0                  26707 non-null  uint8
 48  household_adults_2.0                  26707 non-null  uint8
 49  household_adults_3.0                  26707 non-null  uint8
 50  household_children_1.0                26707 non-null  uint8
 51  household_children_2.0                26707 non-null  uint8
 52  household_children_3.0                26707 non-null  uint8
 53  employment_industry_atmlpfrs          26707 non-null  uint8
 54  employment_industry_cfqqtusy          26707 non-null  uint8
 55  employment_industry_dotnnunm          26707 non-null  uint8
 56  employment_industry_fcxhlnwr          26707 non-null  uint8
 57  employment_industry_haxffmxo          26707 non-null  uint8
 58  employment_industry_ldnlellj          26707 non-null  uint8
 59  employment_industry_mcubkhph          26707 non-null  uint8
 60  employment_industry_mfikgejo          26707 non-null  uint8
 61  employment_industry_msuufmds          26707 non-null  uint8
 62  employment_industry_nduyfdeo          26707 non-null  uint8
 63  employment_industry_phxvnwax          26707 non-null  uint8
 64  employment_industry_pxcmvdjn          26707 non-null  uint8
 65  employment_industry_qnlwzans          26707 non-null  uint8
 66  employment_industry_rucpziij          26707 non-null  uint8
 67  employment_industry_saaquncn          26707 non-null  uint8
 68  employment_industry_vjjrobsf          26707 non-null  uint8
 69  employment_industry_wlfvacwt          26707 non-null  uint8
 70  employment_industry_wxleyezf          26707 non-null  uint8
 71  employment_industry_xicduogh          26707 non-null  uint8
 72  employment_industry_xqicxuve          26707 non-null  uint8
 73  employment_occupation_ccgxvspp        26707 non-null  uint8
 74  employment_occupation_cmhcxjea        26707 non-null  uint8
 75  employment_occupation_dcjcmpih        26707 non-null  uint8
 76  employment_occupation_dlvbwzss        26707 non-null  uint8
 77  employment_occupation_emcorrxb        26707 non-null  uint8
 78  employment_occupation_haliazsg        26707 non-null  uint8
 79  employment_occupation_hfxkjkmi        26707 non-null  uint8
 80  employment_occupation_hodpvpew        26707 non-null  uint8
 81  employment_occupation_kldqjyjy        26707 non-null  uint8
 82  employment_occupation_mxkfnird        26707 non-null  uint8
 83  employment_occupation_oijqvulv        26707 non-null  uint8
 84  employment_occupation_pvmttkik        26707 non-null  uint8
 85  employment_occupation_qxajmpny        26707 non-null  uint8
 86  employment_occupation_rcertsgn        26707 non-null  uint8
 87  employment_occupation_tfqavkke        26707 non-null  uint8
 88  employment_occupation_ukymxvdu        26707 non-null  uint8
 89  employment_occupation_uqqtjvyb        26707 non-null  uint8
 90  employment_occupation_vlluhbov        26707 non-null  uint8
 91  employment_occupation_xgwztkwe        26707 non-null  uint8
 92  employment_occupation_xqwwgdyp        26707 non-null  uint8
 93  employment_occupation_xtkaffoo        26707 non-null  uint8
 94  employment_occupation_xzmlyyjv        26707 non-null  uint8
dtypes: float64(23), int64(3), uint8(69)
memory usage: 7.3 MB

In [113]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, hamming_loss

X = dff.drop(columns=['respondent_id', 'xyz_vaccine', 'seasonal_vaccine'])
y_xyz = dff[['xyz_vaccine']]
y_ssnl = dff[['seasonal_vaccine']]

In [138]:
X_train, X_test, y_train, y_test = train_test_split(X, y_xyz, test_size=0.2, random_state=42)
preprocessor = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),  # Example: Impute missing values with mean
])
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

gb_clf_xyz = GradientBoostingClassifier(n_estimators=150, max_depth=5, random_state=42)
gb_clf_xyz.fit(X_train_processed, y_train)

# Predict on test data for seasonal_vaccine
y_pred_xyz = gb_clf_xyz.predict(X_test_processed)
accuracy = accuracy_score(y_test, y_pred_xyz)
print('xyz acc',accuracy*100)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

xyz acc 85.36128790715088

In [142]:
X_train, X_test, y_train, y_test = train_test_split(X, y_ssnl, test_size=0.2, random_state=42)
preprocessor = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),  # Example: Impute missing values with mean
])
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

gb_clf_seasonal = GradientBoostingClassifier(n_estimators=200, max_depth=5, random_state=42)
gb_clf_seasonal.fit(X_train_processed, y_train)

# Predict on test data for seasonal_vaccine
y_pred_seasonal = gb_clf_seasonal.predict(X_test_processed)
accuracy = accuracy_score(y_test, y_pred_seasonal)
print('ssnl acc',accuracy*100)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ssnl acc 79.23998502433545

In [130]:
y_pred_prob_seasonal = gb_clf_seasonal.predict_proba(X_test_processed)
# Print probabilities of each class being 1 (for the first few samples)
print(f"Probabilities of each class being 1 for the first few samples:\n{y_pred_prob_seasonal[:, 1][:5]}")

Probabilities of each class being 1 for the first few samples:
[0.22123952 0.14047725 0.89062747 0.22821412 0.15624921]

In [131]:
df_test = pd.read_csv("C:\\Users\\Admin\\Downloads\\dataset and all\\test_set_features.csv")
df_test.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"> $75,000",Not Married,Rent,Employed,mlyzmhmf,"MSA, Not Principle City",1.0,0.0,atmlpfrs,hfxkjkmi
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,Non-MSA,3.0,0.0,atmlpfrs,xqwwgdyp
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,"> $75,000",Married,Own,Employed,lrircsnp,Non-MSA,1.0,0.0,nduyfdeo,pvmttkik
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,lrircsnp,"MSA, Not Principle City",1.0,0.0,NaN,NaN
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,lzgpxyit,Non-MSA,0.0,1.0,fcxhlnwr,mxkfnird

In [132]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

cols_to_scale = [
    'opinion_xyz_vacc_effective',
    'opinion_xyz_risk',
    'opinion_xyz_sick_from_vacc',
    'opinion_seas_vacc_effective',
    'opinion_seas_risk',
    'opinion_seas_sick_from_vacc'
]

scaler = MinMaxScaler(feature_range=(0, 1))
df_test[cols_to_scale] = scaler.fit_transform(df_test[cols_to_scale])

print(df_test[cols_to_scale].head())

   opinion_xyz_vacc_effective  opinion_xyz_risk  opinion_xyz_sick_from_vacc  \
0                        1.00              0.00                        0.00
1                        0.75              0.00                        0.00
2                        1.00              0.75                        0.25
3                        0.75              0.25                        0.25
4                        1.00              0.25                        0.75

   opinion_seas_vacc_effective  opinion_seas_risk  opinion_seas_sick_from_vacc
0                         1.00               0.00                         0.00
1                         0.75               0.00                         0.00
2                         1.00               0.75                         0.75
3                         0.75               0.75                         0.25
4                         0.75               0.75                         0.25

In [134]:
df_test['age_group'] = df_test['age_group'].map(age_group_mean_mapping)
print(df_test['age_group'])

0        0.280146
1        0.237296
2        0.377045
3        0.450168
4        0.280146
           ...
26703    0.280146
26704    0.237296
26705    0.237296
26706    0.377045
26707    0.298015
Name: age_group, Length: 26708, dtype: float64

In [136]:
education_mapping = {
    'Unknown': 0,
    '< 12 Years': 0.20,
    '12 Years': 0.40,
    'Some College': 0.60,
    'College Graduate': 0.80
}
df_test['education'] = df_test['education'].map(education_mapping)

In [137]:
import pandas as pd
columns_to_encode = [
    'race', 'sex', 'income_poverty', 'marital_status', 'rent_or_own',
    'employment_status', 'hhs_geo_region', 'census_msa',
    'household_adults', 'household_children', 'employment_industry',
    'employment_occupation'
]
df_test = pd.get_dummies(df_test, columns=columns_to_encode, drop_first=True)

In [150]:
preprocessor = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),  # Example: Impute missing values with mean
])
#df_test.drop(['respondent_id'],axis=1,inplace=True)
df = preprocessor.fit_transform(df_test)
y_pred_xyz = gb_clf_xyz.predict(df)
y_pred_prob_xyz = gb_clf_xyz.predict_proba(df)
print(f"Probabilities of each class being 1 xyz:\n{y_pred_prob_xyz[:, 1][:5]}")

Probabilities of each class being 1 xyz:
[0.06851508 0.0555554  0.11501185 0.74959982 0.26115797]

In [151]:
preprocessor = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),  # Example: Impute missing values with mean
])
df = preprocessor.fit_transform(df_test)
y_pred_seasonal = gb_clf_seasonal.predict(df)
y_pred_prob_seasonal = gb_clf_seasonal.predict_proba(df)
print(f"Probabilities of each class being 1 seasonal:\n{y_pred_prob_seasonal[:, 1][:5]}")

Probabilities of each class being 1 seasonal:
[0.2016915  0.02661239 0.57064963 0.90694154 0.61236659]

In [154]:
df_sbmt = pd.read_csv("C:\\Users\\Admin\\Downloads\\dataset and all\\submission_format.csv")
df_sbmt.head()

   respondent_id
0          26707
1          26708
2          26709
3          26710
4          26711

In [155]:
df_sbmt['h1n1_vaccine'] = y_pred_prob_xyz[:, 1]
df_sbmt['seasonal_vaccine'] = y_pred_prob_seasonal[:, 1]

In [156]:
df_sbmt.head()

   respondent_id  h1n1_vaccine  seasonal_vaccine
0          26707      0.068515          0.201691
1          26708      0.055555          0.026612
2          26709      0.115012          0.570650
3          26710      0.749600          0.906942
4          26711      0.261158          0.612367

In [157]:
df_sbmt.to_csv("C:\\Users\\Admin\\Downloads\\dataset and all\\final_submit.csv")